### ISSUE TITLE
Problem when running playbook - Name or service not known

### ISSUE THREAD

**Issue by MartinTerp** [geerlingguy/awx-container#8] opened 2017-09-09 20:56 UTC
> ERROR! Attempted to execute "/usr/lib/python2.7/site-packages/awx/plugins/inventory/awxrest.py" as inventory script: Inventory script (/usr/lib/python2.7/site-packages/awx/plugins/inventory/awxrest.py) had an execution error: HTTPConnectionPool(host='awxweb', port=8052): Max retries exceeded with url: /api/v1/inventories/2/script/?hostvars=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x2220e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))

This error comes when i try and run a template/playbook.

If i create a alias, for the awx_web link, on the awx_task composer, i get this error instead:

> fatal: [XXX.dk]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: No user exists for uid 1000\r\n", "unreachable": true}

So i added the "user: root" to the awx_task composer, and it ran with success!

My awx_task composer thingy now looks like this (marked with bold what i added/changed):

>   awx_task:
    image: "geerlingguy/awx_task:latest"
    links:
      - rabbitmq
      - memcached
      **- awx_web:awxweb**
      - postgres
    hostname: awx
    **user: root**
    container_name: awx_task
    environment:
      SECRET_KEY: aabbcc
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211

I could create a pullrequest, but i want to know if anyone else is seeing this error, and if this fix helped.

**Comment by jaredledvina** [comment] 2017-09-10 03:34
Confirming that for any Playbook I'm seeing the same behaviour:
```
ERROR! Attempted to execute "/usr/lib/python2.7/site-packages/awx/plugins/inventory/awxrest.py" as inventory script: Inventory script (/usr/lib/python2.7/site-packages/awx/plugins/inventory/awxrest.py) had an execution error: HTTPConnectionPool(host='awxweb', port=8052): Max retries exceeded with url: /api/v1/inventories/2/script/?hostvars=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1c69e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
3
None
```

Looks like `user: root` was already added: https://github.com/geerlingguy/awx-container/blob/master/docker-compose.yml#L51 but, I'll give the `- awx_web:awxweb` a shot

**Comment by jaredledvina** [comment] 2017-09-10 03:42
Yep! That fixes it!

**Comment by geerlingguy** [comment] 2017-09-10 03:59
@jaredledvina / @MartinTerp - Do you think I should change the hostname internally for the awx container to `awx_web` too then? If so, I can generate a new image and you can test. I vaguely remember running into this same issue with one of my own playbooks in a test AWX environment on a plane earlier today.

**Comment by geerlingguy** [comment] 2017-09-10 04:00
And yes, I added the `user: root` in https://github.com/geerlingguy/awx-container/issues/7

**Comment by MartinTerp** [comment] 2017-09-10 12:07
I think so yes, just to align all the names.

i didt add "user: root" to awx_task in the first place, since i didt see any issues at that time.

**Comment by jaredledvina** [comment] 2017-09-10 18:06
@geerlingguy - That makes sense to me, happy to give the image a shot on my personal setup as well.

**Comment by geerlingguy** [comment] 2017-09-11 03:27
Yep, I'll get this fixed in a few minutes I hope (but it will take a bit to rebuild the image and push it...). I can confirm the current images are giving:

```
ERROR! Attempted to execute "/usr/lib/python2.7/site-packages/awx/plugins/inventory/awxrest.py" as inventory script: Inventory script (/usr/lib/python2.7/site-packages/awx/plugins/inventory/awxrest.py) had an execution error: HTTPConnectionPool(host='awxweb', port=8052): Max retries exceeded with url: /api/v1/inventories/2/script/?hostvars=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x2a4fd90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by geerlingguy** [comment] 2017-09-11 03:34
Actually, it looks like the `settings.py` file that ships with AWX has `INTERNAL_API_URL = 'http://awxweb:8052'`, so it would be annoying to try to switch everything to `awx_web`. Therefore, it may be as easy as just setting the links correctly inside the docker-compose.yml file. Testing that now.

**Comment by geerlingguy** [comment] 2017-09-11 04:16
Fixed via above commit.

**Closed as completed** 2017-09-11 04:16 UTC
